org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.vfs.watch=true
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17


# Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]

# NeoForge
neo_version=21.1.209
neo_version_range=[21.1.207,)
loader_version_range=[4,)

# JEI
jei_version=19.21.0.247

## Mod Properties
mod_id=flintspark
mod_name=Flintspark
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.evandev.flintspark
mod_authors=Evan
mod_description=

## Dependencies

# Biolith
bt_version=3.0.10
bt_version_range=[3.0.9,)

# No Man's Land
nml_version=1.4.6

# Cobblemon
cobblemon_version=1.7.3

# Kotlin Forge
kotlin_forge_version=5.11.0

# Dye Depot
dye_depot_version=2.0.2
